
#Application name and port
spring.application.name=demo
server.port = 8080

#H2 Database connection config
spring.datasource.url = jdbc:h2:mem:eshop_db;DB_CLOSE_DELAY =- 1; DB_CLOSE_ON_EXIT = FALSE
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.name = spark
spring.datasource.password =

#Console config
spring.h2.console.enabled = true
spring.h2.console.path = /h2-console

#JPA && Hibernate config
spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto = update
springjpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true